### ISSUE TITLE
Update content: Clients

### ISSUE THREAD

**Issue by chriswhawkins** [b2io/base2.io#103] opened 2017-06-08 15:26 UTC
https://docs.google.com/a/base2.io/document/d/1yPEmKByTSslxJtNSxhWhghD5gO_f1YSQMpJAVXj79PU/edit?usp=sharing

update in google doc and PR

**Comment by kalongthewires** [comment] 2017-11-17 19:55
Duplicate of #93. Updated 93 to include items in the Google Doc.

**Closed by kalongthewires** 2017-11-17 19:55 UTC
Labels: priority: 2-high, scope: content, status: 0-inbox, type: chore
