### ISSUE TITLE
Open Positions section does not have max-width set

### ISSUE THREAD

**Issue by mewdriller** [b2io/base2.io#414] opened 2019-07-31 17:17 UTC
The content for the [Open Positions](https://www.base2.io/jobs/#positions) section doesn't have a max-width set and therefore reads a little less clearly. It looks like the other sections have a max-width of `1200px` set.

Open Positions
![image](https://user-images.githubusercontent.com/492553/62232632-b2ee3c80-b394-11e9-8d1a-ca3af05ba0df.png)

vs.

We Believe In Balance
![image](https://user-images.githubusercontent.com/492553/62232674-cac5c080-b394-11e9-987f-6c540abe6fec.png)

**Comment by mewdriller** [comment] 2019-07-31 18:06
🕵 It looks like the max-width is set [here in `atoms/Section.jsx`](https://github.com/b2io/base2.io/blob/master/src/components/atoms/Section.jsx#L13). I think the underlying issue is that the `<Section />` component only applies those styles when the `narrow` prop is sent. Only [the "Open Positions" section](https://github.com/b2io/base2.io/blob/master/src/components/organisms/jobs/JobsContent.jsx#L74) doesn't have that prop set.

 It would _probably_ be better to describe the max-width in terms of `em` so that it's a [better approximation of readability](https://baymard.com/blog/line-length-readability).

**Comment by tborres** [comment] 2019-08-07 20:29
This is a duplicate of #415 (I hadn't noticed that this issue had been created)

**Closed by tborres** 2019-08-07 20:29 UTC
